---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: fibonacci
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/instance: fibonacci
