---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: fibonacci
spec:
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: fibonacci
  ports:
    - name: http
      port: 8080
      targetPort: 8080
