---
# Pulls NEW_RELIC_LICENSE_KEY from Azure Key Vault via the cluster-level ClusterSecretStore.
# The resulting secret is consumed by the deployment as envFrom.secretRef: fibonacci-secret.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fibonacci-secret
  labels:
    app.kubernetes.io/name: fibonacci-service
    app.kubernetes.io/instance: fibonacci
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore
  target:
    name: fibonacci-secret
    creationPolicy: Owner
  data:
    - secretKey: NEW_RELIC_LICENSE_KEY
      remoteRef:
        key: new-relic-license-key
